language: node_js
node_js:
  - "10.24"
  - "11.0"
  - "12.0"
  - "13.7"
  - "14.0"
  - "15.0"
sudo: false
script:
  - npm run test
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.13.3
    npm run coverage
